#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "SkillPath Sprint 4 — local dev auth setup"
say "This gets Supabase Auth working in local dev: CLI, a hosted project,"
say "and the local emulator stack. Deployment (Render/Vercel/hosted keys)"
say "is a separate wizard, run later once Sprint 4's code is ready to ship."

# ── Stage 1: Supabase CLI via npx ──────────────────────────────────────────
stage "Supabase CLI"
say "We use npx so nothing needs a global install — npm is already on this machine."
if npx --yes supabase@latest --version >/tmp/supabase-version.txt 2>&1; then
  step "Supabase CLI is reachable via npx: $(cat /tmp/supabase-version.txt)"
else
  warn "npx supabase failed to run. Install manually and re-run this wizard:"
  note "  Windows (Scoop): scoop bucket add supabase https://github.com/supabase/scoop-bucket.git && scoop install supabase"
  note "  https://supabase.com/docs/guides/cli/getting-started"
  exit 1
fi
pause "Continue?"

# ── Stage 2: supabase init ─────────────────────────────────────────────────
stage "Initialize Supabase in this repo"
if [[ -f supabase/config.toml ]]; then
  step "supabase/ already initialized — skipping."
else
  say "Creates supabase/config.toml and supabase/migrations/."
  npx supabase init
  step "Initialized."
fi
pause "Continue?"

# ── Stage 3: hosted project ────────────────────────────────────────────────
stage "Create your hosted Supabase project"
say "This is the real project — where the deployed app's data and users live."
open_url "https://supabase.com/dashboard/projects"
step "Sign in (GitHub or email) if you haven't already."
step "Click 'New project'. Name it e.g. 'skillpath'."
step "Set a database password — write it down, you'll need it again shortly."
step "Pick a region close to you, then create the project and wait ~2 min."
step "Once it's ready: gear icon → Project Settings → General → copy 'Reference ID'."
ask SUPABASE_PROJECT_REF "Paste the project reference ID:"
ask_secret SUPABASE_DB_PASSWORD "Paste the database password you just set:"
write_env SUPABASE_PROJECT_REF "$SUPABASE_PROJECT_REF"
write_env SUPABASE_DB_PASSWORD "$SUPABASE_DB_PASSWORD"
note "Hosted API keys (anon/service_role/JWT secret) aren't needed yet —"
note "the later deploy wizard will grab those from this same project."

# ── Stage 4: CLI login ──────────────────────────────────────────────────────
stage "Log in to the Supabase CLI"
say "Links the CLI to your Supabase account so it can reach your project."
say "This opens a browser — approve access, then return here."
npx supabase login
step "Login complete."
pause "Continue?"

# ── Stage 5: link ────────────────────────────────────────────────────────────
stage "Link this repo to your hosted project"
say "You may be prompted for the database password from Stage 3 — paste it when asked."
npx supabase link --project-ref "$SUPABASE_PROJECT_REF"
step "Linked."
pause "Continue?"

# ── Stage 6: start local stack ───────────────────────────────────────────────
stage "Start the local Supabase stack"
say "Docker-based local emulator (Postgres + Auth + Studio). First run pulls"
say "images and can take a few minutes. Its output ends with a table of URLs/keys."
npx supabase start
step "Copy the values from the table above into the prompts below."
ask SUPABASE_LOCAL_URL "API URL (http://127.0.0.1:...):"
ask SUPABASE_LOCAL_ANON_KEY "anon key:"
ask_secret SUPABASE_LOCAL_SERVICE_ROLE_KEY "service_role key:"
ask SUPABASE_LOCAL_DB_URL "DB URL:"
write_env SUPABASE_LOCAL_URL "$SUPABASE_LOCAL_URL"
write_env SUPABASE_LOCAL_ANON_KEY "$SUPABASE_LOCAL_ANON_KEY"
write_env SUPABASE_LOCAL_SERVICE_ROLE_KEY "$SUPABASE_LOCAL_SERVICE_ROLE_KEY"
write_env DATABASE_URL "$SUPABASE_LOCAL_DB_URL"
note "Wrote DATABASE_URL so backend/db.py picks up the local Supabase Postgres"
note "automatically — no other backend .env change needed."
ENV_FILE="frontend/.env.local" write_env NEXT_PUBLIC_SUPABASE_URL "$SUPABASE_LOCAL_URL"
ENV_FILE="frontend/.env.local" write_env NEXT_PUBLIC_SUPABASE_ANON_KEY "$SUPABASE_LOCAL_ANON_KEY"
note "Also wrote NEXT_PUBLIC_SUPABASE_URL/ANON_KEY to frontend/.env.local."

finish
say "Local dev is ready: real Supabase Auth running locally, no hosted-project"
say "quota used. Next: implement Sprint 4's plan against this local stack."
say "When it's time to deploy, run the (separate) deploy wizard for"
say "Render + Vercel + the hosted project's production keys."
